### ISSUE TITLE
CNExT - VISIT_OCCURRENCE_ID Not Pulled From Same Source Consistently

### ISSUE THREAD

**Issue by lvarnedoe** [UNMCCC/CRIIS_Source_Extracts_for_OMOP#59]
The value for VISIT_OCCURRENCE_ID is pulled from differing places throughout the CNExT scripts. I would think it should be pulled from the same source or the equivalent of the value in that source across the board for consistency sake and for cross-referencing purposes.

cnext_condition_occurrence:            VISIT_OCCURRENCE_ID = Hospital.UK
cnext_device_exposure 
cnext_visit_detail
cnext_visit_occurrence

cnext_drug_exposure:                     VISIT_OCCURRENCE_ID = Patient.UK
cnext_procedure_occurrence 

cnext_measurement:                       VISIT_OCCURRENCE_ID = Tumor.FK1
cnext_note 
cnext_observation

According to the DB Repeating Tables Diagram, Patient.UK and Tumor.FK1 should be equivalent, but Hospital.UK would not be equivalent to Patient.UK or to Tumor.FK1.

**Comment by markmayer** [comment]
I'm glad this problem was brought up. We use VISIT_OCCURRENCE_ID to correlate records back to the VISIT_OCCURRENCE table. As Tumor seems to be the common source for most, if not all queries I propose this:

In VISIT_OCCURRENCE change the VISIT_OCCURRENCE_ID to come from TUM.UK.

Also make the same change to any other tables, so that VISIT_OCCURRENCE_ID comes from TUM.UK
